
name: add contributor

on: push


jobs:
  contributor:
    if: 1==2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-cool/contributor-helper@v1.2.0
        with:
          token: ${{ secrets.MYTOKEN }}
          update-files: 'README.md'
          update-places: '## Contributors List/## LIC'
          style: 'simple'
          avatar-width: '40'
          show-total: 'true'

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git pull
          git add -A
          git commit -m "🤖 Auto update contributors" || exit 0
          git push
