
name: add contributor

on: push


jobs:
  add:
    runs-on: ubuntu-latest
    if: 1 == 2
    steps:
      - uses: bubkoo/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
          round: true
          avatarSize: 20
  contributor_list:
    if: 1 == 2
    name: Contributor List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://cjdenio/contributor_list:latest

  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-cool/contributor-helper@v1.2.0
        with:
          token: ${{ secrets.MYTOKEN }}
          update-files: 'README.md'
          update-places: '## Contributors List/## LIC'
          style: 'simple'
          avatar-width: '40'
          show-total: 'false'

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git pull
          git add -A
          git commit -m "🤖 Auto update contributors" || exit 0
          git push
