
name: add contributor

on: push


jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: |
          sudo git clone https://.:${{ secrets.TOKEN2 }}@github.com/${{ github.repository }}.git
          git config --global user.email "zhuanghong.chen@zilliz.com"
          git config --global user.name "zhuanghong.chen"
          sudo chmod -R 777 ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
          pwd
          ls
          echo ${{ github.workspace }}
        
      - name: get and updage contributors 
        uses: milvus-io/hero-bot@dco-enabled
        with:
          token: ${{ secrets.TOKEN2 }}
          repos: 'sutcalag/testaction'
          targetFile: './README.md'
          customUserConfig: 'sutcalag/testaction/aa.json'
          isAscend: False
          width: '50px'
    
      - name: commit code
        run: |
          cd ${{ github.event.repository.name }}
          pwd
          git add -u
          git commit -s -m 'update contributors'
          git push
       


