
name: add contributor

on: push


jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: milvus-io/hero-bot@1.5
        with:
          token: ${{ secrets.MYTOKEN }}
          repos: |
             'milvus-io/milvus'
             'facebook/react,ax'
          target: 'sutcalag/testaction/README.md'
          customUserConfig: 'sutcalag/testaction/aa.json'
        
