
name: add contributor

on: push


jobs:
  contributor:
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
      - uses: milvus-io/hero-bot@1.2
        with:
          token: ${{ secrets.MYTOKEN }}
          repos: 'milvus-io/milvus,milvus-io/www.milvus.io'
          targetRepo: 'sutcalag/testaction'
          

      - uses: milvus-io/hero-bot@1.5
        with:
          token: ${{ secrets.MYTOKEN }}
          repos: 
            - milvus-io/milvus
            - facebook/react,ax
          target: sutcalag/testaction/README.md
          customUserConfig: sutcalag/testaction/aa.json
          
