
name: add contributor

on: push


jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        run: |
          sudo git clone https://.:${{ secrets.FULL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          sudo chmod -R 777 ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
        
      - uses: milvus-io/hero-bot@dco-enabled
        with:
          token: ${{ secrets.FULL_ACCESS_TOKEN }}
          repos: 'milvus-io/milvus'
          targetFile: 'README.md'
          customUserConfig: 'sutcalag/testaction/aa.json'
          isAscend: False
          width: '50px'
      - name: commit code
        run: |
          if git diff --exit-code; then
            git add -u
            git commit -s -m 'update contributors'
            git push
          fi


