
name: add contributor

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
    
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-add contributors
        uses: BobAnkh/add-contributors@v0.0.8
