
name: add contributor

on: push


jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: milvus-io/hero-bot@1.11
        with:
          token: ${{ secrets.MYTOKEN }}
          repos: 'milvus-io/milvus;facebook/react,ax'
          target: 'sutcalag/testaction/README.md'
          customUserConfig: 'sutcalag/testaction/aa.json'
          isAscend: False
          width: '50px'
        

