# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths:
      - 'package.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERPWD }}
  
      - name: Build and push
        run: |
          docker build -t xiaohongczh/test1:preview -f ./Dockfile .
          docker push xiaohongczh/test1:${GITHUB_REF##*/}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
