name: Upload Document as Artifact

on: [push]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish PDF Document
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'docs/*.md'
#       - name: Upload Document
#         uses: actions/upload-artifact@v2
#         id: upload-document
#         with:
#           name: 'document.pdf'
#           path: ${{ steps.publish-document.outputs.pdf }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: 'add doc pdf'
          add: ${{ steps.publish-document.outputs.pdf }}
